# Get a path from the current position to the goal Pose 

# The start pose for the plan
geometry_msgs/Pose start

# The final pose of the goal position
geometry_msgs/Pose goal

---
bool success
nav_msgs/Path path
